export const fonts = [
  'Abril Fatface',
  'Playfair Display',
  'Bebas Neue',
  'Caveat Brush',
  'Signika',
  'Dancing Script',
  'Pacifico',
  'Amatic SC',
  'Itim',
  'Londrina Shadow',
  'Arimo',
  'Poppins',
  'Tinos',
] as const;
