name: Publish and Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.outputs.VERSION }}
      PATH: ${{ steps.outputs.PATH }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm
      
      - name: version
        id: env
        run: |
          echo -e "//registry.npmjs.org/:_auth=${{secrets.NPM_AUTH_TOKEN}}\nemail=${{secrets.EMAIL}}\nalways-auth=true" >> .npmrc
          VERSION=$(npm version patch --no-git-tag-version)
          VERSION="${VERSION:1}"
          echo ::set-output name=VERSION::$VERSION
          PATH="package.json"
          echo ::set-output name=PATH::$PATH
      

      - name: Changes to Package.json
        run: |
          sed -Ei 's!(\s*"version"\:) (.*)!\1 "${{ steps.env.outputs.VERSION}}",!i' ${{ steps.env.outputs.PATH }}

      - run: npm ci
      - run: |
          CI=false npm run build

      

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}