name: Publish and Build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.outputs.VERSION }}
      PATH: ${{ steps.outputs.PATH }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm
      - run: npm ci
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: "Aigotsrl/RC-Shared-Components-Frontend"
          ref: main
          token: ${{ steps.secrets.outputs.GITHUB_TOKEN }}
          persist-credentials: false
          fetch-depth: 0
      - name: version
        run: |
          VERSION=$(npm version patch)
          echo ::set-output name=VERSION::$VERSION
      - name: Changes to Helm Chart
        run: |
          sed -Ei 's!(\s*"version"\:) (.*)!\1 ${{ build.steps.outputs.VERSION}}!i' ${{ build.steps.outputs.PATH }}

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}