name: Publish and Build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.outputs.VERSION }}
      PATH: ${{ steps.outputs.PATH }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm
      - run: npm ci
      - name: version
        id: env
        run: |
          CI=false npm run build
          echo -e "//registry.npmjs.org/:_auth=${{secrets.NPM_AUTH_TOKEN}}\nemail=${{secrets.EMAIL}}\nalways-auth=true" >> .npmrc
          VERSION=$(npm version patch --no-git-tag-version)
          VERSION="${VERSION:1}"
          echo ::set-output name=VERSION::$VERSION
          PATH="package.json"
          echo ::set-output name=PATH::$PATH

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: "Aigotsrl/RC-Shared-Components-Frontend"
          ref: develop
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      - name: Changes to Package.json
        run: |
          sed -Ei 's!(\s*"version"\:) (.*)!\1 ${{ steps.env.outputs.VERSION}}!i' ${{ steps.env.outputs.PATH }}

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "[CI] ${GITHUB_REPOSITORY} - ${GITHUB_WORKFLOW}: ${{ steps.env.outputs.VERSION }}" -a
          git push origin develop

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}