name: Publish and Build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies and build
        run: |
          npm install -g npm@latest
          npm ci
          CI=false npm run build


      - name: Set up .npmrc & publish 
        run: |
          echo -e "//registry.npmjs.org/:_auth=${{secrets.NPM_AUTH_TOKEN}}\nemail=${{secrets.EMAIL}}\nalways-auth=true" >> ~/.npmrc
          npm version patch --no-git-tag-version 
          npm init --scope=@aigotsrl
          npm publish
      

        
